PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Rank (RankID INTEGER PRIMARY KEY, Name, MsgPrefix, MsgSuffix, MsgNameColorCode);
INSERT INTO "Rank" VALUES(1,'Default','','','');
INSERT INTO "Rank" VALUES(2,'VIP','','','');
INSERT INTO "Rank" VALUES(3,'Operator','','','');
INSERT INTO "Rank" VALUES(4,'Admin','','','');
CREATE TABLE PlayerRank (PlayerUUID, PlayerName, RankID INTEGER);
CREATE TABLE PermGroup (PermGroupID INTEGER PRIMARY KEY, Name);
INSERT INTO "PermGroup" VALUES(1,'Default');
INSERT INTO "PermGroup" VALUES(2,'Kick');
INSERT INTO "PermGroup" VALUES(3,'Teleport');
INSERT INTO "PermGroup" VALUES(4,'Everything');
CREATE TABLE RankPermGroup (RankID INTEGER, PermGroupID INTEGER);
INSERT INTO "RankPermGroup" VALUES(1,1);
INSERT INTO "RankPermGroup" VALUES(2,3);
INSERT INTO "RankPermGroup" VALUES(3,3);
INSERT INTO "RankPermGroup" VALUES(3,2);
INSERT INTO "RankPermGroup" VALUES(4,4);
INSERT INTO "RankPermGroup" VALUES(1,1);
CREATE TABLE PermissionItem (PermGroupID INTEGER, Permission);
INSERT INTO "PermissionItem" VALUES(1,'core.help');
INSERT INTO "PermissionItem" VALUES(1,'core.build');
INSERT INTO "PermissionItem" VALUES(3,'core.teleport');
INSERT INTO "PermissionItem" VALUES(2,'core.kick');
INSERT INTO "PermissionItem" VALUES(4,'*');
INSERT INTO "PermissionItem" VALUES(1,'skyblock.command');
CREATE TABLE RestrictionItem (PermGroupID INTEGER, Permission);
CREATE TABLE DefaultRank (RankID INTEGER);
INSERT INTO "DefaultRank" VALUES(1);
COMMIT;
